---
# This play book does a complete setup of the stackato cluster
# Please note that no care has yet been taken to provide idempotentency
# although stackato appears to be pretty lenient for re-executing the same commands

      - hosts: cloudcontrollers
        vars:
        - external_dns_name: xdocker.xebia.dynanic-dns.net
        - admin_email: mvanholsteijn@xebia.com
        - admin_password: Welkom123!
        - admin_organization: Xebia Nederland B.V.

        tasks:
        - name: rename node
          shell: kato node rename {{external_dns_name}} --no-restart && touch .rename.task.done creates=.rename.task.done
        - name: core setup
          shell: kato node setup core api.{{external_dns_name}} && touch .core.task.done creates=.core.task.done
        - name: set license
          shell: kato license set {{stackato_license}} && touch .setlicense.task.done creates=.setlicense.task.done
        - name: enable license
          shell: kato license enable && touch .enablelicense.task.done creates=.enablelicense.task.done
        - name: first user
          shell: 'kato node setup firstuser "{{admin_email}}"  "{{admin_organization}}" --username "{{admin_email}}" --password "{{admin_password}}" &&  touch .firstuser.task.done creates=.firstuser.task.done'
          ignore_errors: yes

      - hosts: services
        tasks:
        - name: rename node
          shell: kato node rename  `ec2metadata --local-ipv4`.xip.io --no-restart && touch .rename.task.done creates=.rename.task.done
        - name: attach as data-services
          shell: kato node attach -e data-services 10.0.3.5 && touch .attach.task.done creates=.attach.task.done

      - hosts: deas
        tasks:
        - name: rename node
          shell: kato node rename  `ec2metadata --local-ipv4`.xip.io --no-restart && touch .rename.task.done creates=.rename.task.done
        - name: attach as dea
          shell: kato node attach -e dea 10.0.3.5 && touch .attach.task.done creates=.attach.task.done

      - hosts: routers
        tasks:
        - name: rename node
          shell: kato node rename  `ec2metadata --local-ipv4`.xip.io --no-restart && touch .rename.task.done creates=.rename.task.done
        - name: attach as router
          shell: kato node attach -e router 10.0.3.5 && touch .attach.task.done creates=.attach.task.done
        - name: attach as router
          shell: kato config set router2g prevent_x_spoofing false && touch .spoofing.task.done creates=.spoofing.task.done
