---
#
# This play book allows stackato user to sudo without password
#
      - hosts: all
        sudo: True
        vars: 
        - ansible_sudo_pass: stackato
        tasks:

        - name: Copy sudoers file for safety
          shell: cp -f /etc/sudoers /etc/sudoers.tmp  && cp -f /etc/sudoers /etc/sudoers.bak

        - name: make sure we can sudo as stackato user
          lineinfile: "dest=/etc/sudoers.tmp state=present regexp='^stackato' line='stackato ALL=(ALL) NOPASSWD : ALL'"

        - name: also make sure ssh-agent works via sudo
          lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'
        - name: install new sudoer file
          shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers ; rm /etc/sudoers.tmp

        - name: change stackato password
          shell: "(echo '{{admin_password}}'; echo '{{admin_password}}' ) | sudo passwd stackato"
